# Generated by Django 3.2.6 on 2021-09-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of the movie.', max_length=100)),
                ('date', models.DateField(verbose_name='date the movie was released.')),
            ],
        ),
    ]
